sudo: required

language: node_js

node_js:
  - 14

services:
  - docker

before_install:
  - docker build -t gioshara/dockerized-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true gioshara/dockerized-react-app npm run test