sudo: required

language: node_js

node_js:
  - 14

services:
  - docker

before_install:
  - docker build -t gioshara/dockerized-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true gioshara/dockerized-react-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "dockerized-react-app"
  env: "Dockerizedreactapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-311534292817"
  docker: "dockerized-react-app"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
